CREATE DATABASE SENAI_SPMEDICALDROUP
GO

USE SENAI_SPMEDICALDROUP;
GO


--TIPO DE USUARIO
CREATE TABLE TipoUsuario(
	IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	TituloTipoUsuario VARCHAR(20) NOT NULL
);
GO

--USUARIO
CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario TINYINT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	NomeUsuario VARCHAR(30) NOT NULL,
	Email VARCHAR(256) NOT NULL,
	Senha VARCHAR(20) NOT NULL
);
GO

--PACIENTE
CREATE TABLE UsuarioPaciente(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) UNIQUE NOT NULL,
	Telefone VARCHAR(14),
	Endereco VARCHAR(256) NOT NULL,
	DataNascimento DATE NOT NULL,
	Rg VARCHAR(12) NOT NULL UNIQUE,
	Cpf VARCHAR(14) NOT NULL UNIQUE
);
GO

--CLINICA
CREATE TABLE Clinica(
	IdClinica SMALLINT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(30) NOT NULL,
	RazaoSocial VARCHAR(75) NOT NULL,
	Endereco VARCHAR(256) NOT NULL,
	Cnpj VARCHAR(18) NOT NULL UNIQUE,
	HorariodeAbertura TIME NOT NULL,
	HorariodeFechamento TIME NOT NULL
);
GO

--ESPECIALIDADE
CREATE TABLE Especialidade(
	IdEspecialidade SMALLINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(55) NOT NULL
);
GO

--MEDICO
CREATE TABLE Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) UNIQUE NOT NULL,
	IdClinica SMALLINT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	IdEspecialidade SMALLINT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL,
	Crm VARCHAR(8) NOT NULL UNIQUE
);
GO

--CONSULTA
CREATE TABLE Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES UsuarioPaciente(IdPaciente) NOT NULL,
	IdSituacao TINYINT FOREIGN KEY REFERENCES Situacao(IdSituacao) DEFAULT(3),
	DataeHora DATETIME NOT NULL,
	Descricao VARCHAR(100)
);
GO

--SITUACAO
CREATE TABLE Situacao(
	IdSituacao TINYINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(15) NOT NULL
);
GO